[package]
name = "myrustlib"
version = "0.1.0"
authors = ["Tom Selfin <selfint@gmail.com>"]
edition = "2018"

[lib]
name = "string_sum"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.12.3"
features = ["extension-module"]

